# Generated by Django 4.2.4 on 2023-08-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon_class', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('TT', 'Tools / Technologies'), ('LF', 'Languages / Frameworks')], max_length=2)),
                ('level', models.CharField(choices=[('P', 'Proficient'), ('F', 'Familiar')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('profile_url', models.URLField()),
                ('icon_class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user_profile/')),
                ('name', models.CharField(max_length=100)),
                ('resume_url', models.URLField()),
                ('social', models.ManyToManyField(to='portfolio.social')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('skills', models.ManyToManyField(to='portfolio.skill')),
            ],
        ),
    ]
