# Generated by Django 4.2.4 on 2023-08-12 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='profile_url',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'mailto'])]),
        ),
    ]
