# Generated by Django 4.2.4 on 2023-08-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_social_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='profile_url',
            field=models.URLField(),
        ),
    ]
