# Generated by Django 4.2.4 on 2023-08-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_social_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='stevenha75@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
