# Generated by Django 4.2.4 on 2023-08-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_image_alter_theme_favicon_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favicon_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
