# Generated by Django 4.2.4 on 2023-08-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_delete_theme_userprofile_favicon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
